# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Sphinx
sphinx:
   configuration: docs/conf.py

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"
  jobs:
    pre_install:
      - uv run plotly_get_chrome -y

# Python
python:
  install:
    - method: uv
      command: sync
      groups:
        - docs

# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html for
# more details on customising builds.
